version: '3.9'
services:
    nginx:
        container_name: nginx
        depends_on:
            - frontend
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: './nginx/dev'
        ports:
            - "3050:80"
    frontend:
        container_name: frontend
        stdin_open: true
        build:
            dockerfile: docker/Dockerfile.dev
            context: '.'
        volumes:
            - /app/node_modules
            - .:/app